Bugfixes! (#516)
* formatting JS

* audio config script

very rough draft of a script to configure .asoundrc very easily

* Update conf-audio.sh

removed some of the messy echos in the code

* Update conf-audio.sh

edited the file a little too quick before running out to dinner... its fixed now...

* added tvshows service

fixed spacing

* removed  param, added configurable refresh interval

* add capability to use multiple hotwords for activation. fixes #442

* formatting config

* fix rss config read error. resolves #409

* fix traffic errors. don't make requests with empty key string

* 0.0.6

* add basic client side error logging

* protip for validating config

* fix reminders. resolves #438

* Update README.md

added Feature Requests and Suggestions to the readme.md...

* Update README.md

* Update README.md

* Bug Fix #457 (#458)

HOTFIX #457

* set a default format language as an english because bing maps API wnats the value of 'dateTime' as 'PM' or 'AM'

* use sonus ^0.1.2 fixes #462

* Add pt-BR Locale

* use https on YouTube #471

* add Johnny five support (#464)

* adding johnny-five functionality for motion detection

* quick fix missing comma

* add info to config.example.js

* quick fix for change config.motion.type to config.motion.mode

* add commas

* add ipcRenderer to autosleep.js

* add spawn commands for motion spotter

* ipcrenderer fix

* further ipcrendering attempts

* ipcrenderer fix

* add script for monitor on/off.

* add script

* Update pi-install.sh

* remove some of the console.errors prior to ipc send... add calibrated IPC

* Add Enabled/disabled function...

removed model and mode from config since proximity will not function properly.

* Add fix for voice commands
in en.json regarding autosleep

* Update package.json

updated `package.json` to match the current file in `dev`

* Update package.json

* add comma

* Update config.example.js

* Update package.json

* Update config.example.js

* Smart mirror patch 0.0.7

* manual changes from #479 (#483)

* manual changes from #479

spacing

* agnostic autoTimer at exit

auto timer

* remove projectId requirement in config. (#484)

* remove projectId requirement in config.

sonus.js will now use the keyfile to load the project ID.

sonus.js will now check to make sure the model file exists and default to snowboy.umdl if it does not.

* fix config.language

* Update sonus.js

* corrected config.js path on line 4

* hotword helper function

* initial refactor

breaking out view components and refactoring weather

about halfway through refactoring

about halfway through refactoring

fixing timer

fixing timer

rss

rss

soundcloud

scrobble

clean up and finish refactor

removing dupe

mend

* use plugin tree for dir structure

* moving pt local

fixing qr plugin

* Smart mirror remote (#450)

* add voice remote for mirror

add connected/disconnected events

* remote devtools kiosk reload

* expose mirror remote IP and port

* expose mirror remote IP and port

* remote connection state management

* add visual breakpoint for JS in index.html

* Adding QR functionality using googleapis charts

this will need to be revised as google can end use of this as it is depreciated...  This is more to provide a way of testing the concept and not delay development of the config pages...

* Committing remaining changes for QRservice

* Patch conflicts

* Update config.js

* Delete config.example.js

* Add files via upload

* Update index.html

* missed a <<<

* moving pt local

fixing qr plugin

* merge configUI from bill

renaming

disable motion by default

move master to default config name

fixing default

patch index

removing config.js

re-adding fs to index.html

config fix

removing js

finishing sonus merge

merging configUI from bill

* Patch Sleep Functionality

 *  removed "Screen On" & "Screen Off" voice commands
 *  removed "Wake Up" voice command
 *  "Sleep" voice command now calls AutoSleepService.sleep function
* Hotword now wakes the mirror by turning on screen if it is sleeping.

* config schema per plugin

* add reboot functionality for remote

* adding maker channel (HomeAutomation, IFTTT, Custom HTTP Requests, etc)

* Update config.schema.json

Prepared config.schema.json for next push from `justbill2020/config-form-improvements`

* squash commit from justbill2020/config-form-improvements

Major changes outlined below:

1) added order key to form[] array so that general, speech, and remote
   are at the top of the config form. also allows for more defined
   ordering of form elements in the future.

2) added config.schema.json for tvshows plugin.

3) manually defined "remote{}" to config in main.js if config.json is
   not found. this can be done other ways... if config.json is not
   found currently it will display a white screen. this should instead
   display the qrcode and remote link. stopped working on forcing that,
   will leave getting that to work to Evan.

4) fixed variable used to merge form[] and value{} from each config.schema.js

5) configFN changed to configPath

6) don't app.quit on failing to load config.json

* adding smart mirror first run

* when a new config is written, relaunch

* ensure config works after configuration

* mobile style fix

* fix autosleep variables wakeCmd and sleepCmd

* motion fix & looking into RSS issue

* get more error info on config.html ...

...when jsonForm fails

* move deps for jsonForm to https://gitcdn.xyz

* use sonus 0.1.4+

* 0.0.8

* Readme update for discourd and docs

remote colin in readme

spelling

* remote menu and ui fixes

* Update config.schema.json

* simple script to agrigate config files

better file names

* use videoSyndicated for YouTube search

* remove npm-platform-dependencies

* fixing merge issue

* some cleanup

* Updating discord link in README.

* remove random jQuery include

* Update remote.js

* Center suggestions

* [FIX] Return labels for recurring events

[Finishes: #408]

* simple update command

* Fix "in progress"

* fix angular error...

...when multiple tv shows are not found.
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
No response for show: big bang theory
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: show in tvshows, Duplicate key: string:, Duplicate value:
http://errors.angularjs.org/1.5.9/ngRepeat/dupes?p0=show%20in%20tvshows&p1=string%3A&p2=
    at angular.js:68
    at ngRepeatAction (angular.js:30441)
    at $watchCollectionAction (angular.js:17617)
    at Scope.$digest (angular.js:17755)
    at Scope.$apply (angular.js:18021)
    at done (angular.js:12002)
    at completeRequest (angular.js:12211)
    at XMLHttpRequest.requestLoaded (angular.js:12139)

* Update motion.js

same update as earlier for master branch... only now on dev branch

* fix issue on TVs displaying no signal

fixes #505

* interim commit

* finally got it

might be hacky but it works... lets clean it up later... this is a hot fix afterall

* Hotfix for missing section configUI

fixes #512

* Update pi-install.sh

removed stale code `cp config.example.js config.js`

* Update install complete message

* Update config.default.json

added defaults for all items... this should import blanks when configuring smart-mirror. not when running smart-mirror.

* Remove geoPosition from default config